export interface Hackathon {
  id: string;
  name: string;
  organizer: string;
  banner: string;
  prizePool: string;
  prizePoolUSD: number; // for filtering
  mode: "Online" | "Offline" | "Hybrid";
  registrationDeadline: string; // ISO date
  submissionDeadline: string;
  resultDate: string;
  teamSize: { min: number; max: number };
  tags: string[];
  platform: string;
  platformUrl: string;
  description: string;
  bookmarked?: boolean;
}

export const HACKATHONS: Hackathon[] = [
  {
    id: "sih-2026",
    name: "Smart India Hackathon 2026",
    organizer: "Ministry of Education, India",
    banner: "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
    prizePool: "₹1 Crore+",
    prizePoolUSD: 120000,
    mode: "Offline",
    registrationDeadline: "2026-08-01",
    submissionDeadline: "2026-09-20",
    resultDate: "2026-10-05",
    teamSize: { min: 2, max: 6 },
    tags: ["AI", "AgriTech", "GovTech", "IoT", "HealthTech"],
    platform: "SIH Portal",
    platformUrl: "https://www.sih.gov.in",
    description:
      "India's flagship national-level hackathon bringing students together to solve real-world government and industry problem statements.",
  },
  {
    id: "eth-global-delhi-2026",
    name: "ETHGlobal Delhi 2026",
    organizer: "ETHGlobal",
    banner: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800&q=80",
    prizePool: "$500,000",
    prizePoolUSD: 500000,
    mode: "Offline",
    registrationDeadline: "2026-07-25",
    submissionDeadline: "2026-08-05",
    resultDate: "2026-08-07",
    teamSize: { min: 1, max: 4 },
    tags: ["Web3", "DeFi", "ZK", "NFT", "Solidity"],
    platform: "ETHGlobal",
    platformUrl: "https://ethglobal.com",
    description:
      "48-hour Ethereum hackathon in New Delhi — build the future of decentralized finance and digital ownership.",
  },
  {
    id: "devpost-ai-2026",
    name: "AI Innovation Challenge 2026",
    organizer: "Devpost × OpenAI",
    banner: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80",
    prizePool: "$200,000",
    prizePoolUSD: 200000,
    mode: "Online",
    registrationDeadline: "2026-07-30",
    submissionDeadline: "2026-08-20",
    resultDate: "2026-09-01",
    teamSize: { min: 1, max: 5 },
    tags: ["AI", "ML", "LLM", "Agents", "OpenAI"],
    platform: "Devpost",
    platformUrl: "https://devpost.com",
    description:
      "Build AI-powered applications using the latest language models, computer vision, and agentic workflows.",
  },
  {
    id: "dorahacks-web3-2026",
    name: "DoraHacks Web3 Global Hackathon",
    organizer: "DoraHacks",
    banner: "https://images.unsplash.com/photo-1620778182530-703effa65a05?w=800&q=80",
    prizePool: "$1,000,000",
    prizePoolUSD: 1000000,
    mode: "Online",
    registrationDeadline: "2026-08-10",
    submissionDeadline: "2026-09-10",
    resultDate: "2026-09-25",
    teamSize: { min: 1, max: 5 },
    tags: ["Web3", "DeFi", "Layer2", "Cosmos", "Polkadot"],
    platform: "DoraHacks",
    platformUrl: "https://dorahacks.io",
    description:
      "The world's largest Web3 hackathon with $1M in prizes across 20+ blockchain tracks.",
  },
  {
    id: "mlh-fall-2026",
    name: "MLH Fall Hackathon Season",
    organizer: "Major League Hacking",
    banner: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&q=80",
    prizePool: "$50,000",
    prizePoolUSD: 50000,
    mode: "Hybrid",
    registrationDeadline: "2026-09-01",
    submissionDeadline: "2026-09-28",
    resultDate: "2026-10-01",
    teamSize: { min: 1, max: 4 },
    tags: ["Beginner-Friendly", "Open Theme", "ML", "Web", "Mobile"],
    platform: "MLH",
    platformUrl: "https://mlh.io",
    description:
      "MLH's flagship fall season — 36 hours, global participants, beginner-friendly tracks with mentors on standby.",
  },
  {
    id: "unstop-cybersec-2026",
    name: "Unstop CyberShield Hackathon",
    organizer: "Unstop × CERT-In",
    banner: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    prizePool: "₹15 Lakhs",
    prizePoolUSD: 18000,
    mode: "Online",
    registrationDeadline: "2026-07-28",
    submissionDeadline: "2026-08-18",
    resultDate: "2026-08-25",
    teamSize: { min: 2, max: 4 },
    tags: ["Cybersecurity", "CTF", "Networking", "Reverse Engineering"],
    platform: "Unstop",
    platformUrl: "https://unstop.com",
    description:
      "India's premier cybersecurity hackathon — tackle real-world threat scenarios, forensics, and zero-day challenges.",
  },
  {
    id: "devfolio-iot-2026",
    name: "Devfolio IoT Builders 2026",
    organizer: "Devfolio × Qualcomm",
    banner: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
    prizePool: "₹10 Lakhs",
    prizePoolUSD: 12000,
    mode: "Hybrid",
    registrationDeadline: "2026-08-05",
    submissionDeadline: "2026-09-05",
    resultDate: "2026-09-15",
    teamSize: { min: 2, max: 6 },
    tags: ["IoT", "Embedded", "Hardware", "Edge AI", "Arduino"],
    platform: "Devfolio",
    platformUrl: "https://devfolio.co",
    description:
      "Build connected hardware and edge AI solutions — from smart agriculture to industrial automation.",
  },
  {
    id: "hackerearth-ml-sprint-2026",
    name: "HackerEarth ML Sprint 2026",
    organizer: "HackerEarth",
    banner: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    prizePool: "$30,000",
    prizePoolUSD: 30000,
    mode: "Online",
    registrationDeadline: "2026-08-15",
    submissionDeadline: "2026-09-15",
    resultDate: "2026-09-22",
    teamSize: { min: 1, max: 3 },
    tags: ["ML", "Data Science", "Python", "Kaggle-style", "NLP"],
    platform: "HackerEarth",
    platformUrl: "https://hackerearth.com",
    description:
      "A month-long machine learning competition focused on NLP, computer vision, and tabular data challenges.",
  },
  {
    id: "hack2skill-health-2026",
    name: "HealthTech Hackathon 2026",
    organizer: "Hack2Skill × Apollo",
    banner: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    prizePool: "₹20 Lakhs",
    prizePoolUSD: 24000,
    mode: "Offline",
    registrationDeadline: "2026-08-20",
    submissionDeadline: "2026-09-25",
    resultDate: "2026-10-10",
    teamSize: { min: 2, max: 5 },
    tags: ["HealthTech", "MedTech", "AI", "Wearables", "Diagnostics"],
    platform: "Hack2Skill",
    platformUrl: "https://hack2skill.com",
    description:
      "Innovate at the intersection of healthcare and technology — diagnostics, telemedicine, mental health, and beyond.",
  },
  {
    id: "luma-climate-2026",
    name: "Climate Tech Hackathon",
    organizer: "Luma × Breakthrough Energy",
    banner: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    prizePool: "$75,000",
    prizePoolUSD: 75000,
    mode: "Online",
    registrationDeadline: "2026-07-22",
    submissionDeadline: "2026-08-10",
    resultDate: "2026-08-20",
    teamSize: { min: 1, max: 5 },
    tags: ["ClimaTech", "Sustainability", "GreenTech", "Carbon", "Renewable"],
    platform: "Luma",
    platformUrl: "https://lu.ma",
    description:
      "Build solutions tackling climate change — from carbon capture software to renewable energy optimization.",
  },
  {
    id: "devpost-game-jam-2026",
    name: "Global Game Jam 2026",
    organizer: "Devpost × Unity",
    banner: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&q=80",
    prizePool: "$25,000",
    prizePoolUSD: 25000,
    mode: "Online",
    registrationDeadline: "2026-08-25",
    submissionDeadline: "2026-09-20",
    resultDate: "2026-09-28",
    teamSize: { min: 1, max: 5 },
    tags: ["GameDev", "Unity", "Unreal", "Indie", "Web Gaming"],
    platform: "Devpost",
    platformUrl: "https://devpost.com",
    description:
      "48-hour game jam — any engine, any platform. From browser games to VR experiences.",
  },
  {
    id: "mlh-open-source-2026",
    name: "MLH Open Source Fellowship Hack",
    organizer: "Major League Hacking",
    banner: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&q=80",
    prizePool: "$15,000",
    prizePoolUSD: 15000,
    mode: "Online",
    registrationDeadline: "2026-09-05",
    submissionDeadline: "2026-09-30",
    resultDate: "2026-10-05",
    teamSize: { min: 1, max: 4 },
    tags: ["Open Source", "Beginner-Friendly", "GitHub", "OSS", "Community"],
    platform: "MLH",
    platformUrl: "https://mlh.io",
    description:
      "Contribute to open-source projects and build your own OSS tools. Great for first-time hackathon participants.",
  },
  {
    id: "eth-global-singapore-2026",
    name: "ETHGlobal Singapore 2026",
    organizer: "ETHGlobal",
    banner: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80",
    prizePool: "$300,000",
    prizePoolUSD: 300000,
    mode: "Offline",
    registrationDeadline: "2026-09-10",
    submissionDeadline: "2026-10-05",
    resultDate: "2026-10-07",
    teamSize: { min: 1, max: 4 },
    tags: ["Web3", "ZK", "DeFi", "Account Abstraction", "Layer2"],
    platform: "ETHGlobal",
    platformUrl: "https://ethglobal.com",
    description:
      "Build cutting-edge Ethereum applications in the heart of Asia's crypto capital — Singapore.",
  },
  {
    id: "unstop-fintech-2026",
    name: "FinTech Hackathon 2026",
    organizer: "Unstop × HDFC Bank",
    banner: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    prizePool: "₹25 Lakhs",
    prizePoolUSD: 30000,
    mode: "Hybrid",
    registrationDeadline: "2026-08-01",
    submissionDeadline: "2026-09-01",
    resultDate: "2026-09-15",
    teamSize: { min: 2, max: 5 },
    tags: ["FinTech", "Payments", "Blockchain", "AI", "UPI"],
    platform: "Unstop",
    platformUrl: "https://unstop.com",
    description:
      "Revolutionize banking and payments — from AI-driven fraud detection to next-gen UPI experiences.",
  },
  {
    id: "dorahacks-ai-agent-2026",
    name: "AI Agent Hackathon 2026",
    organizer: "DoraHacks × Anthropic",
    banner: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80",
    prizePool: "$250,000",
    prizePoolUSD: 250000,
    mode: "Online",
    registrationDeadline: "2026-07-31",
    submissionDeadline: "2026-08-28",
    resultDate: "2026-09-05",
    teamSize: { min: 1, max: 4 },
    tags: ["AI", "Agents", "LLM", "Automation", "Claude"],
    platform: "DoraHacks",
    platformUrl: "https://dorahacks.io",
    description:
      "Build autonomous AI agents that reason, plan, and act. Use any LLM framework — LangChain, AutoGen, Claude, or roll your own.",
  },
];

export const ALL_TAGS = Array.from(
  new Set(HACKATHONS.flatMap((h) => h.tags)),
).sort();

export const AI_RECOMMENDATIONS: { hackathonId: string; reason: string }[] = [
  {
    hackathonId: "dorahacks-ai-agent-2026",
    reason: "Matches your AI & LLM skills on GitHub",
  },
  {
    hackathonId: "devpost-ai-2026",
    reason: "Based on your previous AI hackathon participation",
  },
  {
    hackathonId: "sih-2026",
    reason: "Popular among developers in your city (Mumbai)",
  },
];
